#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
    path: /api/login
# config/routes.yaml
api_refresh_token:
    path: /api/token/refresh
# ...
api_token_invalidate:
    path: /api/token/invalidate